Issue 33 preview link
bynicodevelop/atrapio pull request #46
Opened 2021-12-15 18:55 UTC by bynicodevelop

2021-12-15 20:47 UTC, bongouade commented on lib/screens/link_details_screen.dart
> +          child: _view(context, args),
Une virgule après args

2021-12-15 20:48 UTC, bongouade commented on lib/screens/link_details_screen.dart
> +        mobile: _view(context, args),
une virgule après args

2021-12-15 20:50 UTC, bongouade commented on lib/screens/link_details_screen.dart
> +          child: _view(context, args),
une virgule après args

2021-12-15 20:54 UTC, bongouade requested changes
Quelque problème de formatage.

2021-12-16 07:29 UTC, bynicodevelop commented on lib/screens/link_details_screen.dart
> +          child: _view(context, args),
Bien vu 👍

2021-12-16 08:43 UTC, merged